version: '2'
services:
    recruit-app:
        image: recruit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://recruit-mysql:3306/recruit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=recruit-elasticsearch:9300
        ports:
            - 8080:8080
    recruit-mysql:
        extends:
            file: mysql.yml
            service: recruit-mysql
    recruit-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: recruit-elasticsearch
